### ISSUE TITLE
[Request] Modify base PAWN string

### ISSUE THREAD

**Issue by Levinaxr** [seriallos/raidbots-issues#12]
_Thanks for an amazing site and utterly incredible service!_

For the extremely convenient feature that lets you quickly export a PAWN string for your stat weights, I'd like to request a simbot level user setting to change the basic name for the string you get, so that for example your PAWN string instead could be just "Spec (Raidbots)" instead of also including the username of the character, or some other possible combinations that some user would prefer more. Say "Raidbots - Spec (Username)".
The ability to either modify this part of the preset string or select from a shorter list of variations to it on a simbot user level would be incredible and much appreciated! :)

Current:
> ( Pawn: v1: "**Username** - **Spec** (**Raidbots**)": Class=DemonHunter, Spec=Havoc, Agility=10.00, CritRating=11.00, HasteRating=10.00, MasteryRating=9.00, Versatility=7.00 )

Example of options:
> ( Pawn: v1: "**Spec** **(Raidbots)**": Class=DemonHunter, Spec=Havoc, Agility=10.00, CritRating=11.00, HasteRating=10.00, MasteryRating=9.00, Versatility=7.00 )

> ( Pawn: v1: "**Raidbots** - **Spec** (**Username**)": Class=DemonHunter, Spec=Havoc, Agility=10.00, CritRating=11.00, HasteRating=10.00, MasteryRating=9.00, Versatility=7.00 )

**Comment by a2line** [comment]
I do a lot of simc with Raidbots and I always feel the need to add my current ilvl or a timestamp to the exported Pawn string because I never know when I made last sim/if a new one would be usefull.

I think it's far more pertinent then username/spec because Pawn already sort my scales by users, and I can pick up colors to materialize the differents specs.

That's just my 2 cents, if you play with this one day... not a real need! Thanks for your dedicated work on Raidbots.

**Comment by seriallos** [comment]
I added some additional controls for the Pawn string:

![image](https://user-images.githubusercontent.com/1010294/49908267-95348d00-fe2e-11e8-92cc-1382433aeae9.png)

Better late than never! :D
