### ISSUE TITLE
Raidbots Iterations 

### ISSUE THREAD

**Issue by runoeune** [seriallos/raidbots-issues#128]
the irritations gets capped out at 12k when i set it to 100k
would appreciate it if this bug could be solved

**Comment by seriallos** [comment]
This is not a bug, it is by design.

When you manually choose Iterations over 25k, it also turns on "target error" mode so that the sim will run until the chosen iterations OR the error reaches 0.05%

Raidbots does not support running sims beyond 0.05% error - it's almost never necessary. If you want to run at even lower error levels, you can download SimulationCraft and use any precision desired.
