### ISSUE TITLE
Pocket-sized Computation device

### ISSUE THREAD

**Issue by Wasyar** [seriallos/raidbots-issues#134]
Atm its really hard to see if this trinket is a upgrade or not especially since when i try to sim it with this red socket in https://gyazo.com/8da80c4e76320ed4661e9ababae4e5d8 on raid bots it only shows it as seen in this 2nd picture https://gyazo.com/8018f50e0b6c91286d7045d1248fe54a

first picture is taken in game and 2nd is taken on raidbots with all addons updated etc so for some reason when i do the /simc and copy it over it lowers the Ilvl and having the wrong stats because even ingame the 404 version has around 1k haste on proc iirc.

**Comment by seriallos** [comment]
It's a tooltip issue but not an issue for the actual results from the sim. Correct values are being used internally for damage calculations.

The punchcards are implemented in a very weird way in-game (the gems have bonus IDs which is unlike anything that has been seen before) and is not supported by Wowhead tooltips. SimC itself is properly receiving and handling these "bonus IDs within bonus IDs" and simulating them properly.

I will probably be disabling tooltips for the trinket and/or the individual punchcards since it's pretty confusing right now.
