### ISSUE TITLE
Auspicious Spirits

### ISSUE THREAD

**Issue by alevshunov** [seriallos/raidbots-issues#136]
Looks like the Shadow Priest's perk [Auspicious Spirits](https://www.wowhead.com/spell=155271/auspicious-spirits) doesn't work or adds only 5% instead of 50% damage.

Perk is used: https://www.raidbots.com/simbot/report/ssZQTWBiWumawgjiJi5uUs
Shadowy Apparitions | 10.9% |   | 651,164 | 78 |  
651k per 78 ticks => 8.346k per tick

Perk not used: https://www.raidbots.com/simbot/report/5dN6DfEjt9Z68VV1znYjrs
Shadowy Apparitions | 10.7% |   | 651,217 | 80 |
651k per 80 ticks => 8.138k per tick

The difference in damage per tick is less than 5% when the perk is used vs when not.

Expectation: the damage should be increased by 50%.

_Did i miss something?_

**Comment by seriallos** [comment]
Talked to the shadow priest simc dev / theorycrafter and he said that there some non-obvious-but-intended interaction between Shadowy Apparitions (the talent) and Spiteful Apparitions (the azerite trait). The Azerite ends up doing more damage when you aren't talented into Shadowy Apparitions which is why the two sims end up being fairly similar and this does match in-game behavior.
