### ISSUE TITLE
7th Legionnaire's Chainmail

### ISSUE THREAD

**Issue by Liukaste** [seriallos/raidbots-issues#144]
7th Legionnaire's chainmail item for hunters does not have the correct azerite traits listed.
Tier 4 ring should contain: Primal instincts, Dance of death, Unerring vision, venomous fangs, blur of talons, steady aim
Tier 3: Serrated jaws, wildfire cluster, rapid reload, battlefield precision
Tier 2: Azerite globules, heed my call, gutripper
Tier 1: Resounding protection, nature's salve

**Comment by seriallos** [comment]
The right piece is there but you have to dig a little due to the complexity of WoW items and limitations of my database.

There are three different 7th Legionnaire's Chainmail items that have existed with different azerite powers over the 8.x patches:

https://www.wowhead.com/search?q=7th+legionnaire%27s+chainmail

If you search for the exact name in Gear Compare you'll see the three items:

![image](https://user-images.githubusercontent.com/1010294/63653158-1bbf9f00-c71e-11e9-8ce2-8c97fcab46d8.png)

In this case, the last one has the right set of Azerite powers:

![image](https://user-images.githubusercontent.com/1010294/63653166-2c701500-c71e-11e9-9d61-fb70e8c8d125.png)
