### ISSUE TITLE
[Request] Cache Top Gear Baseline Data

### ISSUE THREAD

**Issue by AROAH1337** [seriallos/raidbots-issues#146]
When running a Top Gear sim, I'm noticing a good portion of time is spent on generating baseline data, which I assume is simming performance using the gear the character already has.

I'm not sure whether SimC would allow something like this, but I think it would be nice if RaidBots could cache the baseline sim data if it's being run on a character that was previously simmed under the same conditions, just with different combinations selected. Perhaps this data could be tied to a hash of the SimC input to easily check whether anything has changed that would affect the baseline? These hashes could be culled, say, every hour or so, to keep from having a bunch of useless old hashes. Could probably even first check against account name to improve performance, a tad.

I understand that this would require some db space to keep track of everything, so perhaps making this a premium feature would be best, if it were implemented at all. That's assuming it _can_ be implemented. Could also be that this is a much bigger feature idea than I think it is.

**Comment by seriallos** [comment]
It's something I've considered but has been a low priority. My intuition is that it would be a huge amount of technical complexity for marginal gains but I haven't run any experiments to gather data on it.

It's not something that's built into SimC so it would require some form of consistent hashing of actors, a _lot_ of JSON manipulation and storage, and really robust error and cache invalidation handling. The surface area for nasty bugs would be pretty high. Given that a single actor usually only takes seconds to process, I don't think it would result in particularly significant gains in overall processing since large sims are often hundreds (or thousands) of actors. Add to that SimC changes happen nightly/weekly which would require cache invalidation.

I'm more likely to explore other areas for optimization (alternative optimization algorithms, figure out how to throw even more processing power at the problem, etc) since I believe those could result in larger potential gains and avoid a lot of the potential pitfalls (cache invalidation is hard, etc). Actor caching is not something I've totally ruled out, just something that strikes me as _probably_ a less effective use of time/resources compared to other approaches.
