### ISSUE TITLE
Azerite traits - only outer ring taken into consideration

### ISSUE THREAD

**Issue by te1bl** [seriallos/raidbots-issues#158]
If you sim Azerite gear, it seems only the outer ring is taken into consideration.

Here is an example:
https://www.raidbots.com/simbot/report/9x6mfRKpbTNQvWUYbw87JZ

If you sim any of the new Azerite items, you will see the best trait went from the outer ring to the second ring, therefore a definite upgrade doesn't seem so good anymore.

If you look at this sim please see the Pauldrons of the Great Convergence.

https://www.raidbots.com/simbot/report/pdemNkyMiVtXekG7swegLP

The outer Ring is Elemental Whirl, the difference of that trait between 430 and 475 about 1700 dps according to herodamage: https://www.herodamage.com/demon-hunter/azerite-levels/1t-t25-havoc

This is nearly the exact differece of dps by itemlevel for the entire item calculated by raidbots, which cannot be the case since furious gaze also adds nearly 2k dps only by that item level difference.

Hope that explains it well.

Best Regards

PS: Tried the same with simcraft, so this seems to be a simcraft bug.

**Comment by seriallos** [comment]
HeroDamage and Bloodmallet use the generic raid profiles, not your specific character, so comparisons to your own character aren't apples-to-apples.

Here's a sim of your character that shows that each trait is affecting DPS, just in different amounts to the charts on HD - I've set up some of the same pieces as in your sim but have variations without some of the traits removed:

https://www.raidbots.com/simbot/report/4Tae27rdabqfozGKz1P5bZ

This should clearly show that all 3 powers sim significantly higher than only one or two traits selected which indicates that all of them affect DPS in the sim, not just the outer trait.

The HD sims have some other differences to your sim as well - slightly longer fight (6 minutes instead of 5 minutes), much higher item level (T25 profiles are ilevel 478 compared to your 444), different essences (including the 4th essence slot on the raid profile), slightly different talents (Master of the Glaive instead of Unleashed power), and different trinkets.

Generic sims are meant to serve as a rough ranking of powers/talents/etc, not as an absolute reference for your character.
