### ISSUE TITLE
Missing gear item

### ISSUE THREAD

**Issue by Kazoo626** [seriallos/raidbots-issues#163]
I have a set of "Deadwash Gauntlets", but the only item spelled close to that is Deadwash Greaves, nothing else under Deadwash G...., so I can't sim my new gear piece

**To Reproduce**

**Expected behavior**

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment]
This is a funny one. There's a typo in the item name in the actual game data from Blizzard. The name of the item in the client data is "Deadwash..Gauntlets" (spaces have been replaced by periods). So it has two spaces instead of one.

For the moment, you can find the item by searching just for "deadwash" or if you include the two space by searching for "deadwash  gauntlets" (two spaces in there).

I haven't seen this before so I'd guess it's pretty rare. I'll make a note to look into this in more depth to see if there's anything I can do to help address it.

**Comment by Kazoo626** [comment]
That is funny.  Thanks so much.
