### ISSUE TITLE
Can't link bot to my Discord

### ISSUE THREAD

**Issue by AeicorWoA** [seriallos/raidbots-issues#166]
Recently purchased the epic level of raidbots for my guild to use on discord, and can't link my discord to the bot. I went to my account, selected connect to discord, and authorized. When I select the dropdown for servers, I only see 2 of the 5 servers I'm connected to, neither of which are my guild's discord. I clicked on the "invite the bot to your server" link and nothing shows up in that drop-down either. I have manage server permissions, since I was the one who created the server. Are there other requirements that aren't listed?

**Comment by seriallos** [comment]
You are probably logged into the Discord website as an old account - this happens pretty frequently because Discord has kind of a weird signup flow where you often end up creating two accounts without realizing it.

Go to the Discord website and logout. Then log back in making sure you get logged in as the same user that you use in the Discord client. Then disconnect/reconnect Raidbots and Discord and you should see the right servers.

**Comment by AeicorWoA** [comment]
That fixed it, thank you!
