### ISSUE TITLE
Surging Vitality I sims incorrectly

### ISSUE THREAD

**Issue by aderic** [seriallos/raidbots-issues#177]
Surging Vitality I claims it increases Versatility by 0 for 20 seconds.
![image](https://user-images.githubusercontent.com/1957928/75116691-e9ddb580-5638-11ea-865e-3797cc1b489d.png)

I don't believe this is just a tooltip error though, as the simulation also says cleansing it results in plus or minus of 20-30 DPS, which is within margin of error.

If it helps, the particular item is: 
https://www.wowhead.com/item=159333/cincture-of-the-azerite-arsenal&bonus=5002:41:6578:6579:6558:6515:1622:4786

This is also my particular sim:
https://www.raidbots.com/simbot/report/jRwp6CEDqqPZMMFkG7Fshw

**Comment by seriallos** [comment]
By default, Raidbots/SimC assumes no damage is taken so that corruption provides no DPS benefit and that is the value used in the sim you linked:

![image](https://user-images.githubusercontent.com/1010294/75118112-f4de1900-562b-11ea-84af-c46def8e77b6.png)

There's an option to set the uptime of the buff under Simulation Options:

![image](https://user-images.githubusercontent.com/1010294/75118088-b0eb1400-562b-11ea-86cb-c95e1e9fff00.png)

The uptime can vary quite a bit based on fight / how much damage you take so you'd need to look at logs to figure out the right value for you.

**Comment by aderic** [comment]
I'm surprised Patchwerk doesn't do that.

I'd make one suggestion, just a small QOL for people like me that derp out:
An informational icon on certain items, so that people can know at a glance that they're linked to a separate setting in the simulation options.

Thanks for the heads up.
