### ISSUE TITLE
Character Does Not Appear

### ISSUE THREAD

**Issue by covert80** [seriallos/raidbots-issues#184]
My character Awac-Sargeras (US) will no longer appear in Raidbots. I server transferred days ago, and he is fully updated in WoW's website. However, Raidbots just says "Character not found."

**Comment by seriallos** [comment]
This is an issue with the Blizzard Armory API.  Blizzard uses a different data source for their own website which is why it shows up there but not on Raidbots.

Blizzard's API often seems to have issues getting updates for characters that have server transferred. If your character is not updating after you log out, only thing you can do is wait and hope it updates at some point in the future.

That said, on the website you can always use the SimC addon which will always be up-to-date and doesn't require logging out of the game to get an update.

**Comment by seriallos** [comment]
Responding to the comment you left on a commit message:

> The issue is that the character exists, but I am unable to run a sim. See screenshot and link to the character in WoW's website.

The API that Raidbots has access to does not know about your character. The WoW website uses something different that 3rd parties like Raidbots can't use. So while your character shows up on the WoW website, Raidbots is unable to get that information.

This is an issue with Blizzard's API and I've repeatedly reported these issues to them but haven't seen any improvements.

I still recommend using the SimC addon whenever possible as it contains more info about your character and will not have problems like these.

**Comment by JJTopCat** [comment]
I am a Raidbots subscriber.  I love that website.  It is totally worth the fee to support those who maintain it.  That team deserves every bit.  The fact that you get extra features with your sub is just extra icing on the cake.  

When I run a top gear sim, it puts the same dom shards in different slots on the exact same gear.  Same gear, same shards, but different combinations on where the shard is slotted.  It seems to impact the simulation.  Why would it matter?  Set bonus is active.  Why does leech dom shard need to be in shoulders, instead of belt?
