### ISSUE TITLE
Raidbots and Simcraft giving different results

### ISSUE THREAD

**Issue by Ethos10** [seriallos/raidbots-issues#2]
Getting wildly differing results from Raidbots and directly using Simcraft (by 70k dps). I looked at the results side by side and the only thing I could find was that it looked like Raidbots wasn't simming Wdps and Simcraft was, resulting in a much higher dps for the latter. Is this intentional? It's causing all the stat weights to be different as well.

**Comment by seriallos** [comment]
Sorry for the delay, I'm a doofus and didn't have notifications set up properly.

Without more information (URL to Raidbots report and a copy/screenshot of your local report), there are a few candidates from most likely to least likely:

* Different versions of SimC being used locally vs Raidbots
* `fixed_time` defaults to 1 in Raidbots but 0 in the SimC GUI. This mostly effects you if you have Cinidaria equipped as `fixed_time=1` results in more time spent above 90% boss health.
* Custom APL/override differences
* Different input from /simc or Armory

Wdps config shouldn't cause a difference, that just controls whether Wdps is evaluated when determining stat scales. Wdps isn't an issue in Legion since it's directly controlled by Relics/Artifacts.
