### ISSUE TITLE
Shadowgrasp Totem Active is not used when simming DPS

### ISSUE THREAD

**Issue by Nekolover69** [seriallos/raidbots-issues#229]
When simulating DPS with the Shadowgrasp Totem (trinket from De Other Side) equipped, your character will not use the trinket. Below, I have a link to a sim from my hunter, who currently has the totem equipped. In the bottom part, where it shows spell order, you can see that he never uses it. There is also no report of its damage in the DPS calculation.

https://www.raidbots.com/simbot/report/gRFtNiiymXJinoWwRoe9gC

**Comment by seriallos** [comment]
That trinket only got implemented in SimC today: https://github.com/simulationcraft/simc/commit/32752fecdf0cec6adbc743d71800399dfb5f915f

It'll be available in the Nightly SimC Version shortly (rebuild a little later tonight due to some other issues) and it'll come to the weekly version on Monday night / Tuesday morning.
