### ISSUE TITLE
Ritualist's Treasured Ring likely incorrect stats for Heroic

### ISSUE THREAD

**Issue by shelbyd** [seriallos/raidbots-issues#233]
Ritualist's Treasured Ring from Heroic Lady Inerva Darkvein would give the same character less DPS than the normal counterpart.

**To Reproduce**
See:
1. Normal - https://www.raidbots.com/simbot/report/6UDqz91NerkqKpEtjY8jQX
2. Heroic - https://www.raidbots.com/simbot/report/qzBfFKNZ3U1cqQK3836pYQ
3. Mythic - https://www.raidbots.com/simbot/report/8PPCydQMdoRFtJq3f1ipRn

Those droptimizer reports are from the same simc output. Notice that the ring from Lady Inerva Darkvein is a DPS loss on heroic, but a gain on normal and mythic.

**Expected behavior**
I expect a ring with strictly more stats to be a better DPS upgrade than one with fewer stats.

**Link a sim with the problem (if available)**
Linked above.

**Comment by seriallos** [comment]
This issue is resolved in the current Nightly SimC build on Raidbots (weekly will be updated tonight). You can see this Droptimizer run using the Nightly build shows the expectation that the higher level ring will be better: https://www.raidbots.com/simbot/report/maukV2irRCUxSCRyy1e52A

The core issue is that there was some funky simulation behavior that could cause pretty big swings in item value based on small differences in haste (so +10 haste would result in less DPS but +20 haste would go way back up).
