### ISSUE TITLE
Unbound Changeling not sim correctly

### ISSUE THREAD

**Issue by Derasiel** [seriallos/raidbots-issues#235]
The trinket [Unbound changeling](https://www.wowhead.com/item=178708/unbound-changeling?bonus=7210:6652:6917:1501:5861:6646&ilvl=203), doesn't get sim correclty, I don't know how, but maybe it's not sim in the correct secondary stats which make it worse than it should be.

It's my bis trinket, it's should sim better than [Soul igniter](https://www.wowhead.com/item=184019/soul-igniter?bonus=7188:6652:1485:6646&ilvl=213) on [this report](https://www.raidbots.com/simbot/report/pNmZ5WKixQWvkkeTdVJGdN).

**Comment by seriallos** [comment]
I'm not aware of any problems with Unbound Changeling in SimC at this time. I've verified in several reports that the trinket is providing the stat buff.

> It's my bis trinket, it's should sim better than Soul igniter on this report.

I'm guessing this evaluation is based on bloodmallet charts (which are also used on wowhead and icy-veins guides). There are some pretty significant differences between the character simmed for the bloodmallet charts and your character - different covenants, different legendaries, and different item level. Those differences are likely changing the relative power ranking. Also, both Bloodmallet and Raidbots are using SimulationCraft under the hood so if you trust bloodmallet, you should trust the more specific results from Raidbots since we are using the same simulation engine.

If I'm mistaken in my assumptions about how you are determining BiS, please let me know and I can look deeper.
