### ISSUE TITLE
Impossible Monk Opener

### ISSUE THREAD

**Issue by Iceysheart** [seriallos/raidbots-issues#253]
**Describe the bug**
Ran quick sim of my monk and when looking thru ability list it used, noticed an ability usage like 7 or 8 seconds in that would cause u to drop to negative chi.
**To Reproduce**

**Expected behavior**
to properly calculate amount of chi at time of ability usage
**Link a sim with the problem (if available)**
https://www.raidbots.com/simbot/report/rZeuYg4VgVTaAGA8UGTtP
If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**
Did multiple sims using top gear trying to compare buffed vs unbuffed amongst other things. Ran a friend's monk thru quick sim to compare our dps and noticed that it gave an exact ability breakdown of what it used for 1 of the sims. Proceeded to do a quick sim of my own monk to try to look thru ability usage to improve my gameplay. It used chi wave (0 chi) fist of white tiger (3 chi) expel harm (4 chi) xuen, weapons of order, and storm, earth, and fire, touch of karma. those 4 ability cause 0 chi, use 0 chi, so still at 4 chi. Then Rising sun kick (2 chi, activates weapons of order 2ndary buff), blackout kick (2 chi), fists of fury (0 chi), blackout kick (0 chi) rising sun kick (-1 chi???) and then I stopped reading cuz it didn't calculate correctly. tested exact sequence on training dummy and 2nd rising sun kick is impossible without a tiger palm first.

**Comment by seriallos** [comment]
I'm not an expert on monks, but it looks like WW sims start at 1 chi and your tests start at 0 chi. Looking at various references ([wowhead](https://www.wowhead.com/windwalker-monk-rotation-guide), [icy veins](https://www.icy-veins.com/wow/windwalker-monk-pve-dps-rotation-cooldowns-abilities), and [peak of serenity](https://www.peakofserenity.com/sl/windwalker/pve-guide/advanced-kyrian/)), they all mention using Expel Harm 10-20 seconds before the fight so that you start at 1 chi.

You can try adding `initial_chi=0` to the "Custom APL and SimC Options" section and run another Quick Sim to see if that ends up matching your expectations. There's also an even more detailed version of the "Sample Ability Log" in the Full HTML Report - it's under Action Priority List > Sample Sequence Table - that table shows energy/chi at every step.

**Comment by seriallos** [comment]
Also, [the SimC project](https://github.com/simulationcraft/simc/issues) itself is likely a better place to ask these kinds of questions as the module developers are there.

The SimcMinMax discord or Peak of Serenity Discord servers also have more experts and likely have more details on hand.

**Comment by seriallos** [comment]
I believe this is resolved, please follow up if you have any more questions.
