### ISSUE TITLE
Altering ilvl of upgradable items being simmed

### ISSUE THREAD

**Issue by nod-dev** [seriallos/raidbots-issues#272]
**Is your feature request related to a problem? Please describe.**
Since 9.0.5 dropped and items can be upgraded through Valor, it is a little more difficult to quickly sim items that you may not have upgraded yet. For example, I currently have a cloak at 203 and I got a drop yesterday at 200. I had to go to Wowhead to find the item ID of the 203 version to be able to see whether I would be better off with my new drop as long as I spent Valor to upgrade it - or if it would still be worse than my current item.

**Describe the solution you'd like**
The ability to choose item level variants of items that are upgradable would be particularly useful. I've attached a very basic HTML hack to try and illustrate the kind of thing that _could_ work, but there may be a better solution to the problem.
![image](https://user-images.githubusercontent.com/14308948/111075348-8d696480-84df-11eb-8cd4-f9bf3de1c5c5.png)

**Describe alternatives you've considered**
So far, I have been using Wowhead to try and find the ID of the higher item level and editing the Simc addon output.

**Comment by seriallos** [comment]
I'm not sure if I will build better support for item upgrades or not, but there are a couple of other approaches you can use.

As a brute force approach, you can use Droptimizer to sim the M+ items at any upgrade level - just pick the right item level and go.

When editing your input, an item always has the same item ID regardless of item level and SimC has an `ilevel=` parameter than can be used for quickly copying an item and changing the item level.

So that cloak would be something like this in your bag (this one is item level 210):

`back=,id=178851,enchant_id=6203,bonus_id=3536/4786/1524`

And you can easily override the item level by using the ilevel= parameter:

``back=,id=178851,enchant_id=6203,bonus_id=3536/4786/1524,ilevel=220`

**Comment by nod-dev** [comment]
I wasn't aware of the `ilevel` parameter - this solution is sufficient for what I'm trying to do. 
Thanks.

**Comment by cremor** [comment]
Although this solution is fine, you need to know about it. A GUI option would make this feature way more discoverable.
@seriallos If adding additional support for this feature is not completely off the table, maybe you could open this issue again so that we he a tracking issue for it?

Btw, a different idea on how to handle this:
Just like there is an option to add x sockets to your gear, there could be an option to upgrade your gear for x valor points.
I understand that this would be more complex than the initial suggestion of this issue, but maybe as a second step?

**Comment by seriallos** [comment]
It's still on my list to look into but I don't have any concrete plans right now.
