### ISSUE TITLE
Show (rough) individual upgrade value right in "Your top gear" paperdoll

### ISSUE THREAD

**Issue by rowaasr13** [seriallos/raidbots-issues#275]
Preface: Yes, I understand that this can show only rough value, since actual value of all items depend on each others.

Problem: while simming several upgrades at once, I still like to scroll down to "Top gear" window with all combination, find rows where each upgrade was tried alone without any other items to get rough understanding what items contributed what to final value. This requires significant mousing around to find all those rows.

Request: can you please show those upgrade contribution values for relevant items directly in topmost "Your top gear" window. Opposite corner of item level in each individual item's box looks like a good place for that.

**Comment by seriallos** [comment]
While I would like to improve several things about Top Gear reports (such as displaying more summary-style analysis like this) at some point in the future, it's definitely a longer term project and won't be happening any time soon.

One thing to be aware of is that combinations that sim lower than the best might have been run at significantly lower precision - Smart Sim runs at 3 precision levels, narrowing down to the best combination and running higher precision sims as it gets closer. If an individual item swap was in the lowest precision pass, it'll have a much larger margin of error (1-2% instead of 0.05%) which makes numbers even more difficult to compare/analyze.

I'll leave this item open as an idea to keep in mind but there are some significant technical hurdles that would need to be solved to handle it properly which I don't currently have any plans to do.

**Comment by rowaasr13** [comment]
Well, yeah - hence "rough". I'd be happy with low precision number simply copied from already calculated results below for now.

Maybe add it hidden behind some checkbox with explanation, so it will be seen only by people who know what to expect and won't be surprised with something like negative numbers in it sometimes?

**Comment by seriallos** [comment]
Closing due to age. The idea is still on my "list of things I'd like to do" but I don't have any specific plans at this time.
