### ISSUE TITLE
Dreadfire Vessel damage wrong

### ISSUE THREAD

**Issue by prosymna85** [seriallos/raidbots-issues#276]
The damage reporting for Dreadfire Vessel (trinket) is incorrect. It shows as 9179 fire damage on your website and in sims, but shows as 10296 in-game. This is a significant difference that is affecting sim numbers. I have provided the /simc info and a link to the result, as well as a screen shot of the trinket equipped in game. Please advise if there is anything additional needed.

```
# Dzoo - Balance - 2021-04-23 15:28 - US/Thunderhorn
# SimC Addon 9.0.5-01
# Requires SimulationCraft 901-01 or newer

druid="Dzoo"
level=60
race=night_elf
region=us
server=thunderhorn
role=spell
professions=enchanting=115/skinning=150
talents=3332112
spec=balance

covenant=night_fae
soulbind=niya:1,322721/279:6/342270/258:6/320668/256:6/254:5/320659
# soulbind=dreamweaver:2,319217/319210/319216/319191
# soulbind=korayn:6,325066/325067/325073/325069
# conduits_available=261:5/262:5/264:5/265:6/266:5/267:6/268:5/269:6/270:5/273:6/275:5/276:5/279:6/274:5/263:5/257:5/258:6/259:6/260:6/254:5/255:6/256:6/271:5/272:5
# renown=40

head=,id=182980,bonus_id=7188/41/7193/1485/6646
neck=,id=178707,gem_id=173130,bonus_id=7389/7359/6652/6935/1540/6646
shoulder=,id=179344,bonus_id=7213/6652/1501/5884/6646
back=,id=178755,enchant_id=6203,bonus_id=7389/7359/6652/1540/6646
chest=,id=178795,enchant_id=6265,bonus_id=7211/6652/1501/5881/6646
wrist=,id=178847,enchant_id=6220,bonus_id=7213/6652/7193/1501/5884/6646
hands=,id=183007,enchant_id=6205,bonus_id=7188/6652/1485/6646
waist=,id=178805,bonus_id=7211/6652/7193/1501/5881/6646
legs=,id=183024,bonus_id=7188/41/1485/6646
feet=,id=172315,enchant_id=6207,bonus_id=7107/6758/6650/6648/1532
finger1=,id=178824,enchant_id=6166,bonus_id=7359/6652/7194/7387/1534/6646
finger2=,id=178736,enchant_id=6170,bonus_id=7210/6652/7193/1501/5878/6646
trinket1=,id=184842,bonus_id=6652/1472/5881/6646
trinket2=,id=184030,bonus_id=7188/6652/1485/6646
main_hand=,id=178714,enchant_id=6228,bonus_id=7417/7359/6652/1540/6646

### Gear from Bags
#
# Condor Headpiece of the Aurora (33)
# head=,id=36039,bonus_id=6654/1706,drop_level=30
#
# Cowl of the Absolute (35)
# head=,id=45435
#
# Phaelia's Vestments of the Sprouting Seed (35)
# chest=,id=45237
#
# Bindings of Yearning (35)
# wrist=,id=40338
#
# Coldwraith Pants of the Fireflash (33)
# legs=,id=36064,bonus_id=6654/1692,drop_level=30
#
# Coldwraith Pants of the Fireflash (33)
# legs=,id=36064,bonus_id=6654/1692,drop_level=30
#
# Coldwraith Boots of the Fireflash (33)
# feet=,id=36060,bonus_id=6654/1692,drop_level=30
#
# Satchel of Misbegotten Minions (226)
# trinket1=,id=178772,bonus_id=7375/7359/6652/1540/6646
#
# Skinning Knife (2)
# main_hand=,id=7005
```

https://www.raidbots.com/simbot/report/fywwWBcf4ZSj13QDfCUN9h

![WoWScrnShot_042321_152648](https://user-images.githubusercontent.com/83095961/115931519-7c016980-a448-11eb-8b20-0c808e932360.jpg)

Thank you.

**Comment by seriallos** [comment]
Tooltips are from Wowhead and are not indicative of the data the sim is using. In this case the tooltips are wrong but the sim is using the correct values.

To see more detail about what SimC is doing, you can run a Quick Sim and look at the full HTML report.

Here's your character: https://www.raidbots.com/simbot/report/fDQit33rDXhQUgExFDXkmV

Looking at the Abilities, you can drill into Dreadfire Vessel in more depth:

<img width="559" alt="image" src="https://user-images.githubusercontent.com/1010294/115948849-7d04bc00-a485-11eb-9d89-e2cefb9131f9.png">

You can see the average value in the sim is about 11k, likely due to interactions with other abilities or buffs. If you compare this to Details or WCL you'll likely see the values will be pretty close.
