### ISSUE TITLE
New Pelagos potency conduit slot is connected to old soulbind ability in Top Gear UI

### ISSUE THREAD

**Issue by cremor** [seriallos/raidbots-issues#280]
**Describe the bug**
The new Pelagos potency conduit slot, which is unlocked at Renown 43 is shown as connected to the old ultimate soulbind ability (which was unlocked at Renown 30), so you can only enable/disable both at the same time.
Additionally, the combination count doesn't notice when the slot gets enabled and therefore doesn't increase.

**To Reproduce**
1. Load the supplied character data.
2. Make sure that "unlock all soulbinds" is enabled so that the new potency conduit slot can be used.
3. Make sure that more than 2 potency conduits are enabled.
4. Try to enable/disable the third potency conduit slot for Pelagos.
5. Notice that you can't do it without also changing the old ultimate soulbind ability and that the combination count doesn't change.

**Expected behavior**
The new potency conduit slot should not be linked to the old ultimate soulbind ability and the combination count should correctly count it.

**Character or /simc input**
For "Load from SimC Addon": https://pastebin.com/Br5EJ9sF

**Screenshots**
![grafik](https://user-images.githubusercontent.com/116314/124076480-96f2ea00-da46-11eb-97ed-54c8ad652bc6.png)

**Additional context**
I haven't tested it but it looks like Dreamweaver and Plague Deviser Marileth have the same problem.

**Comment by cremor** [comment]
I just realized that this isn't a new problem. All conduit slots and soulbind abilities that are connected in the top gear UI are actually separately unlocked ingame. So maybe this is by design?

But even then the combination count should still work correctly.

**Comment by seriallos** [comment]
This is by design. Top Gear groups soulbinds/conduits together based on the path to make it quicker to select full trees of things and ensure a full path is chosen.

It's definitely a bit funky and doesn't gracefully handle this case of partially filled out soulbinds.

The combination count is always at 2 in your described case because of the grouping.

Your equipped soul bind: Let Go of the Past / empty
Select that group: Let Go of the Past / Conduit
Unselect that group: empty / empty

Your equipped soul bind is always simmed and then toggling the group always results in 1 additional choice.

Again, it's not the perfect design but I don't currently have plans on rebuilding it since Top Gear is still able to handle most variations of Soulbind sims.
