### ISSUE TITLE
Ashen Juggernaut 

### ISSUE THREAD

**Issue by Archaosin** [seriallos/raidbots-issues#287]
my issue is general the spell ID is showing the incorrect crit % granted per stack.  In fact its double what it should be i have rank 226 ashen juggernaut and in game it only grants 2% crit.  Now where this is a problem for me is i'm afraid these sims are severely undervaluing my crit strike stat.

**Comment by seriallos** [comment]
Tooltips are from Wowhead and are completely separate from SimC (the open source software that Raidbots runs under the hood).

Wowhead tooltips can sometimes be outdated or buggy but it does not indicate a problem with sims.

The best way to verify what SimC is actually using is to run a simulation that has a Full HTML Report - the easiest to use is Quick Sim. Check the Full HTML Report linked in the sidebar and find the item/spell/ability - you should be able to dig into a detailed table that will include all calculated aspects.

If SimC is actually using a wrong value, you can check with the SimcMinMax Discord or report the issue to the [SimC GitHub project](https://github.com/simulationcraft/simc). Game data is usually updated pretty quickly after patches and announced hot fixes but there can be bugs that sneak in due to how it's used or how Blizz changes the data.
