### ISSUE TITLE
Dungeon Slice sims with Raid Buffs even though it shouldn't

### ISSUE THREAD

**Issue by diab64** [seriallos/raidbots-issues#324]
**Describe the bug**
Dungeon Slice mode says: "Overrides Fight Length, uses buffs from scrolls. Disables raid specific buffs." Accordingly, under the Raid Buffs section, Bloodlust, Arcane Intellect, Power Word: Fortitude, Battle Shout, and Windfury Totem are greyed and crossed out, as intended.

However, on the results page, you can see that it sims with Bloodlust, Arcane Intellect, Power Word: Fortitude, and Battle Shout active.

This is shown in the Top Gear, Quick Sim, and Stat weights sims that I have tested.

**To Reproduce**
Sim any character with Dungeon Slice mode.

**Expected behavior**
Raid Buffs Bloodlust, Arcane Intellect, Power Word: Fortitude, and Battle Shout, should not be taken as active for the sim.

**Link a sim with the problem (if available)**

I have tried this with multiple characters with different sim types/settings, all with Dungeon Slice mode. But here is an example report:

https://www.raidbots.com/simbot/report/w5RqhJT11hymEkmW6MdWam

**Screenshots**
https://i.imgur.com/zk2y1Tv.jpg

![raidbotsbug](https://user-images.githubusercontent.com/44482861/152654825-643678a2-80de-4ee2-9b40-32b9e71f77fd.JPG)

**Comment by cremor** [comment]
"Raid specific buffs" does not mean Fortitude/Intellect/Battle Shout, but literally buffs that are only active in raids (e.g. Domination Shard set effects from last tier).

The reasoning why this is the case is even written directly under the "Dungeon Slice" selection: "uses buffs from scrolls"
Scrolls are not a thing any more, but that's why it was implemented like that back then. Maybe it would be a good thing to update this :grin:

The same is true for Bloodlust, it assumes you use drums.

This is also documented in detail on the page that is linked directly under the "Dungeon Slice" selection: https://medium.com/raidbots/mythic-simming-with-dungeon-slice-68a834880975

So only Windfury Totem is forced to disabled, everything else is forced to enabled.
Maybe it would be better if the Windfury Totem option would be shown as unchecked in the crossed out settings, while the other 4 buffs stay at checked and crossed out.

**Comment by diab64** [comment]
The reason I thought Fortitude/Intellect/Battle Shout were the buffs that were not used was that they are crossed out.

Why is Fortitude/Intellect/Battle Shout unable to be unchecked then? I am simming for dungeons/M+, not raid. I'm never going to have Fortitude, Arcane Intellect, and Battle Shout in one 5-man group. That would mean that every single dungeon I run would have to have a comp that includes a Priest, a Mage, and a Warrior.

**Comment by cremor** [comment]
As I've writtern, the "Dungeon Slice" profile was created back when buff scrolls were a thing. So it assumed that you used scrolls if you didn't have those classes in the group.
Since Shadowlands this doesn't make sense any more. But it looks like nobody changed it yet.

I suggest you create an issue in the Simulationcraft repository (https://github.com/simulationcraft/simc/issues) because Simulationcraft is the component that forces those buffs to be on. Only after Simulationcraft changed Raidbots can be updated to allow changing the options.

**Comment by cremor** [comment]
@seriallos simulationcraft/simc#6708 was just merged, which removes the forced class buffs for dungeon slice. Could you please update the UI to reflect that?

**Comment by seriallos** [comment]
Should be good to go with the caveat/warning that Raidbots will determine which buffs are active since it sets each buff individually.

I think in most cases, all buffs will be active for Dungeon Slice sims by default so it will take user action to set the buffs to match their expected buffs available.

**Comment by cremor** [comment]
@seriallos Minor thing, but could you please also update the help text under the "dungeon slice" selection? It still mentions scrolls.

**Comment by seriallos** [comment]
> @seriallos Minor thing, but could you please also update the help text under the "dungeon slice" selection? It still mentions scrolls.

Done!
