### ISSUE TITLE
Droptimizer Mechagon Dungeons are labeled as PVP rewards

### ISSUE THREAD

**Issue by ajudanta** [seriallos/raidbots-issues#347]
When I´m doing a droptimizer for the two Mechagon Dungeons they are labeled as "PVP SEASON 4 (HONOR)" and "PVP SEASON 4 (CONQUEST)"
![image](https://user-images.githubusercontent.com/93989728/192107617-845c8d36-aa63-4778-9858-137e0e749ea7.png)
![image](https://user-images.githubusercontent.com/93989728/192107661-2302407d-b79b-4902-872c-36d789040af9.png)

**Comment by seriallos** [comment]
Thanks for the report!

Unfortunately, there's some subtle and deep data issues with how Raidbots handles categorizing these items that's unlikely to be fixed during Season 4. I'm hoping to fix the underlying issue so that it doesn't recur in Dragonflight.

I am pretty sure it's just a display issue and shouldn't affect the validity of the actual sims.
