### ISSUE TITLE
Raidbots report shows wrong trinket (correct in simc report)

### ISSUE THREAD

**Issue by leobolin** [seriallos/raidbots-issues#38]
In [this report](https://www.raidbots.com/simbot/report/8fPS8jvfA8PD8ASaDKiidK) you can see that the input uses Horn of Valor as the second trinket, but the page is displaying Arcanocrystal as second trinket. Not sure if this is just a display error or if it actually simmed with the wrong trinket. What's going on?

**Comment by seriallos** [comment]
Appears to be a display issue. SimC used Horn of Valor based on the SimC HTML Report:

![image](https://user-images.githubusercontent.com/1010294/34460540-4403f8a4-edc6-11e7-921e-f6e59df1d486.png)

My current guess is that you hit a timing issue - you probably pasted in the SimC input and hit submit faster than Raidbots could fully look up all your items to populate that data correctly and it ended up using the data from your last SimC input.

I'll take a look into the race condition / display issue and see if I can solve that since it does result in this weird behavior!

**Comment by seriallos** [comment]
This _should_ be fixed. The timing issue should no longer be possible (or very, very rare).
