### ISSUE TITLE
Crafted Engineering helm is simming low.

### ISSUE THREAD

**Issue by battleturkey** [seriallos/raidbots-issues#433]
Whenever running a top gear sim [Peripheral Vision Projectors] ilvl 463 with secondary stats set to mastery are simming very low or The druids heroic helm tier piece is simming way to high. According to the top gear sim it should be an apx 7000dps difference. The simulations also had the LFR version of the druid tier helm outperforming it.

If you have a sim report that shows the problem, please provide the URL here

https://www.raidbots.com/simbot/report/k9vYvXtqFTWYNdbA1H8c4T

**Comment by seriallos** [comment]
The issue is that the Breath of Neltharion tinker is generally not great and it's particularly bad in sims. It usually doesn't have special handling so it ends up being used during Bloodlust which sims particularly poorly. It's a long cast which means that several class abilities won't be used during the best cooldown windows.

Removing Breath shows the engineering helm performing much as expected - the 473 helm is still better but the gap isn't as huge: https://www.raidbots.com/simbot/report/jBXexVSTD36B4eVtcsBaoa

Upgrade it to 473 and it's competitive/better than the Vault helm: https://www.raidbots.com/simbot/report/5BKx7FSRRWNsv3UduwfhdH

I believe the issue with Breath is known to the SimC project but it's non-trivial to solve for a tinker that's not generally preferred.
