### ISSUE TITLE
Network Connectivity

### ISSUE THREAD

**Issue by Ornthorpe** [seriallos/raidbots-issues#443]
A network error occurred. Check your connectivity. I get this error message over half the times I visit Raidbots to sim a character.

**Comment by seriallos** [comment]
This support document covers all the methods to try to determine what and where the problem is: https://support.raidbots.com/article/46-general-troubleshooting

There are no widespread errors on the Raidbots side of things so it's likely an issue with your ISP, your local network, or some software running on your computer. The support article linked above has steps to help determine where the problem is and guidance on trying to figure out what's causing the problem.
