### ISSUE TITLE
"Top Gear" issues

### ISSUE THREAD

**Issue by denisbider** [seriallos/raidbots-issues#5]
My attention was called to RaidBots SimBot by the mention of the Top Gear feature, which would be excellent if it was ready.

The feature does not appear to be ready:

- The number of iterations offered, even with patronage, is insufficient for the feature to be of use. I selected the Epic patronage, and reduced the number of gear choices so that there's 2 options for each normal slot, and 3 for rings and trinkets. This comes out *way* over budget - tens of billions of iterations.

- I then removed choices in slots where I don't have legendaries, leaving only 1 alternative item for each of the 6 slots where I have a choice between legendary and non-legendary. Still way over budget - 5.76 billion iterations.

- At this point, there seemed to be something very funky going on with ring and trinket slots. With 3 choices for rings, and 3 choices for trinkets, I was at 5.76 billion iterations. Removing a *non-legendary* ring *or* trinket (removing any choice for the respective two slots) dropped that to 80k iterations. Removing a *legendary* ring *or* trinket dropped it to 270k iterations.

  It seems really funky that there's an edge case where fixating a slot (rings or trinkets) reduces the load by 72 times. It suggests there might be bugs in how the trinket and ring slots are being handled.

- It does not seem to be possible to restrict candidate combinations to only those that have at least 2-set or at least 4-set. This would radically reduce the number of candidates that need to be tried if it was offered.

Overall, the feature is not useful right now. The prospect of cloud-based SimCraft is very nice, so I'll keep the patronage going, and check again in some time to see if it's useful then. I hope it improves.

**Comment by seriallos** [comment]
* Iteration limits are intentionally very conservative right now to ensure overall stability of the site and ensure that sims that are submitted are completed in a reasonable time. No promises but I am keeping an eye on these and I hope to be able to raise them once I get a better sense of the performance characteristics of the feature.
* There's a hack/estimation in place to solve a nasty performance problem that I ran into late in development of this feature. I'm working on fixing that which should provide much more accurate numbers at high combination levels and selections that result in a large number of sets that don't match constraints.
* Tier piece constraints are also on my list.

**Comment by seriallos** [comment]
Just deployed a fix that should maintain the accuracy of the numbers until 20-30k gearsets are reached. At that point it will just stop computing the combinations because it begins affecting page performance.

**Comment by denisbider** [comment]
Great improvement, very fast, thank you!

At this point, I would still desire a greater iteration budget to make use of the Top Gear feature. After the fix, it's minimally functional to the extent that I can *just about* try to sim for the best legendary combination, *if* I limit myself to one alternative to each legendary, and no choices in other slots.

What I would *really* like to use the feature for, is what it says it's for, which is to find the best gear combo in my bags. For this, I would need a larger iteration budget than 1.6 mil.

Any chance Patreon sponsors can have a daily/weekly/monthly budget, instead of per use?

(Running time tolerance would likely need to be extended, as well.)

**Comment by seriallos** [comment]
Going to close this for now but will add some more notes:

I'm hoping that I can raise the limits in the future but there's a number of technical challenges in the way (long sims are somewhat flaky due to some architectural choices, long sims are expensive to manage, large sims like this are pushing the boundaries of what SimC itself is capable of, etc). I'll continue the medium/long term work on improving this as I can (faster servers, more memory, decomposing large simulations into smaller pieces and running on multiple machines in parallel, etc).

I also have plans to add more methods of constraining the gear sets as mentioned before (maintain set bonuses, lock a ring/trinket in place, etc).

The iterations budget is an interesting idea that I'll keep in mind although I won't be tackling it any time soon. The main challenge is that long sims are inherently flaky and can cause a lot of congestion in the queue which can impact a large number of users. Time limits are my primary method of controlling queue times for all users.  It's not out of the question but I won't be changing the model any time soon.

Fundamentally, it's a difficult problem to solve with SimulationCraft just given the computational resources required. There are some other approaches that some folks are playing with in projects like autosimc to make the problem more tractable. For the time being, it just won't be possible to run all combinations and will require human judgment to narrow the selection down. Your own judgment is important regardless to make sure you understand what's being evaluated and how gear can apply to the content you're playing.
