### ISSUE TITLE
Chrono Shard set almost certainly simming incorrectly

### ISSUE THREAD

**Issue by jeromystewart** [seriallos/raidbots-issues#51]
Hey guys wonderful tool. When I sim "best in bags" set with chrono shard .. often the neck comes up near the top and chrono too .. after many hundreds of simms .. never have the 2 come in at the top in tandem.. in other words (if it isn't obvious) Raidbots/Simc is completely ignoring the set bonus from what I can tell.

**Comment by seriallos** [comment]
Did some quick tests it does look it's being simulated correctly.

My guess is that the additional haste is not worth much for you and so the combo of neck + trinket is never better than alternate items in those slots.

[In this sim](https://www.raidbots.com/simbot/report/kBF9AHVYqJ4rFQ6F8pDkiC) I set up "stat stick" items with the same stats as the set items and then ran the values.

You can see that the fake items are the same DPS as the fake trinket (no proc) and the real neck. This is expected since those two combos have the same raw stats and no proc at all.

"fake neck + trinket" would be the DPS without the set bonus since the neck is just stats.

The "real neck + real trinket" is 0.4% higher for my character which is the result of the set bonus empowering the proc. You can look at the buffs in the Full HTML Report and see that without the set bonus, haste is ~4.7k on the Acceleration buff from the trinket and ~5.7k with the set bonus.

**Comment by jeromystewart** [comment]
I stand corrected, I guess it's just and artifact of BM being so strange this expac. With other specs/classes there are clear winners and losers. With BM there are tons of gearset/talent combos that sim within < 1% of each other. Not cool blizz. .. thanks for your help
