### ISSUE TITLE
Stat weights change each time I run a sim.

### ISSUE THREAD

**Issue by Skittzo** [seriallos/raidbots-issues#56]
I loaded my character information into the stat weight sim using the SimC addon. I then ran the sim and it produced my stat weights. I ran another sim using the same SimC string and same gear and it produced completely different stat weights. I tried running the sim using the armory and it also produced different stat weights with each run using the same character info. Am I doing something wrong?

**Comment by seriallos** [comment]
**Short version:** this is generally expected, Smart Sim should reduce variation, stat weights are a weak measure anyway.

Long Version:

This is somewhat expected and could vary more based on your class/spec. While the absolute values (the specific weight for each stat) can change from run to run, the relative values (the relationship between the stats) are generally consistent and that's fundamentally what's important about stat weights (Stat X is 2x more powerful right now than stat Y).

To reduce variation, try using Smart Sim (open up Simulation Options and choose "Smart Sim") if you're not already using it (it will also be the default choice later today). Smart Sim should produce more consistent results regardless of class/spec though there will still be some variation because of the fundamental RNG of WoW combat.

I'd also suggest not worrying too much about stat weights. Any single result from stat weights generally only applies to your current gear and will change dramatically when gear changes. "Direct" simulations of different gear sets (Top Gear, Gear Compare) are more consistent and more accurate. It can be useful to have some relatively up-to-date stat weights for very quick reference in-game but they honestly fluctuate so often that it's annoying to keep up.

It doesn't look like there are many good write ups about the pros/cons of stat weights so I may write up a blog post at some point going into more detail about this.
