### ISSUE TITLE
top gear bug

### ISSUE THREAD

**Issue by feanor212** [seriallos/raidbots-issues#6]
When i sim for top gear on my character it gives me a list for DPS and TMI.I dont know if it's a visual bug but when swapping between the 2 options,some items that get changed show a different name than the actual tooltip.The item's icon is the one of the item's name though.I've attached a picture with the bug.This is kinda confusing since i cant figure out which one i should be using.
![untitled](https://cloud.githubusercontent.com/assets/28922013/26399321/2fcf8630-4085-11e7-952a-8006bd4ca52b.png)

**Comment by seriallos** [comment]
I'll probably be removing the TMI measure at some point in the near future - it's not very well supported and no one maintaining the tank code is using so it's not particularly reliable/useful right now.  The side effect is that the tooltips won't be weird because you won't be able to change the measure on the screen (it's an update issue with the tooltips - in this particular case, the first time they display they get "stuck at that point)

I believe DPS is default so you should be able to use the tooltips for that since that's the only reliable info for tanks right now anyway (and even DPS for tanks is a bit funky - some of the tank devs are working on improving things and I may be doing some more work to get that all up-to-snuff)
