### ISSUE TITLE
Raid Gear

### ISSUE THREAD

**Issue by Drathe** [seriallos/raidbots-issues#74]
I haven't checked all the Raid gear, but many of the items are showing in the gear compare as "Raid Finder 350 item level".

Uldir LFR gear is 340+ ilvl and Uldir Normal is 355+ ilvl.

Most annoyingly (and the reason to write this) is that clicking the arrows to change the items to a different ilvl does *not* work. It will show whatever ilvl you changed it to (355 in this case), but after the sims have run for the gear compare, it shows that it was actually using the 350 ilvl versions of the items.

**Comment by seriallos** [comment]
Unfortunately, it looks like it's surprisingly tough to get the arrows to work properly with my UI code (Firefox's input arrows don't fire events that I would have thought they would - there seems to be quite a lot of bug reports over the years about the weird Firefox behavior). I'm going to hide the arrows completely so that it's not totally broken.

As for the tooltips, I don't have any plans on changing the current behavior. Gear Compare makes "fake" items that don't have any real concept of where they came from (or if they are warforged, etc). Trying to guess requires a bunch of semi-complex code to match item levels with possible bonus IDs that will also be wrong (ambiguity with higher raid level vs war/titanforge).

Tooltips _should_ be correct for real items from your bags in Top Gear.
