### ISSUE TITLE
Strange simulations

### ISSUE THREAD

**Issue by NECROMADIS** [seriallos/raidbots-issues#96]
Hello, i want help with a strange simulation! I was simulating a guildy who is 5 ilvl less than me, with same trinkets, same race as me and worst weapon+worst azerites+worst neck! Itried to simulate his char with my gear and my char with his to see what happens and here is the srangest he went 6.5% down with mine gear and i went 3.5% dow with his gear! All the other simulatitions machines give me other results thats why i m contacting! Here is the report URL:
https://www.raidbots.com/simbot/report/ax4cb9SDrpsZrJKt8BVm7z
 and here is my characters report URL with he is gear same race and higher neck i went less 
https://www.raidbots.com/simbot/report/7w8VyLDwH7GmCrsrHHbJmH

**Comment by seriallos** [comment]
The first sim was run with Reorigination Array set to 9 so it simmed as if the character was in Uldir. Your gearset does not have any Uldir Azerite powers which is why it simmed so much lower.

I ran the first sim again with Reorigination Array manually set to 0 and it looks more in-line with expectations:

https://www.raidbots.com/simbot/report/37VxL9Xu2xbwwM3JT1nrtg
